package com.unionx.web.company.vo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CompanyShebaoMainbiliCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table company_shebao_mainbili
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table company_shebao_mainbili
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table company_shebao_mainbili
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_shebao_mainbili
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    public CompanyShebaoMainbiliCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_shebao_mainbili
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_shebao_mainbili
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_shebao_mainbili
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_shebao_mainbili
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_shebao_mainbili
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_shebao_mainbili
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_shebao_mainbili
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_shebao_mainbili
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_shebao_mainbili
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_shebao_mainbili
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table company_shebao_mainbili
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMainUuidIsNull() {
            addCriterion("main_uuid is null");
            return (Criteria) this;
        }

        public Criteria andMainUuidIsNotNull() {
            addCriterion("main_uuid is not null");
            return (Criteria) this;
        }

        public Criteria andMainUuidEqualTo(String value) {
            addCriterion("main_uuid =", value, "mainUuid");
            return (Criteria) this;
        }

        public Criteria andMainUuidNotEqualTo(String value) {
            addCriterion("main_uuid <>", value, "mainUuid");
            return (Criteria) this;
        }

        public Criteria andMainUuidGreaterThan(String value) {
            addCriterion("main_uuid >", value, "mainUuid");
            return (Criteria) this;
        }

        public Criteria andMainUuidGreaterThanOrEqualTo(String value) {
            addCriterion("main_uuid >=", value, "mainUuid");
            return (Criteria) this;
        }

        public Criteria andMainUuidLessThan(String value) {
            addCriterion("main_uuid <", value, "mainUuid");
            return (Criteria) this;
        }

        public Criteria andMainUuidLessThanOrEqualTo(String value) {
            addCriterion("main_uuid <=", value, "mainUuid");
            return (Criteria) this;
        }

        public Criteria andMainUuidLike(String value) {
            addCriterion("main_uuid like", value, "mainUuid");
            return (Criteria) this;
        }

        public Criteria andMainUuidNotLike(String value) {
            addCriterion("main_uuid not like", value, "mainUuid");
            return (Criteria) this;
        }

        public Criteria andMainUuidIn(List<String> values) {
            addCriterion("main_uuid in", values, "mainUuid");
            return (Criteria) this;
        }

        public Criteria andMainUuidNotIn(List<String> values) {
            addCriterion("main_uuid not in", values, "mainUuid");
            return (Criteria) this;
        }

        public Criteria andMainUuidBetween(String value1, String value2) {
            addCriterion("main_uuid between", value1, value2, "mainUuid");
            return (Criteria) this;
        }

        public Criteria andMainUuidNotBetween(String value1, String value2) {
            addCriterion("main_uuid not between", value1, value2, "mainUuid");
            return (Criteria) this;
        }

        public Criteria andCompanyUuidIsNull() {
            addCriterion("company_uuid is null");
            return (Criteria) this;
        }

        public Criteria andCompanyUuidIsNotNull() {
            addCriterion("company_uuid is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyUuidEqualTo(String value) {
            addCriterion("company_uuid =", value, "companyUuid");
            return (Criteria) this;
        }

        public Criteria andCompanyUuidNotEqualTo(String value) {
            addCriterion("company_uuid <>", value, "companyUuid");
            return (Criteria) this;
        }

        public Criteria andCompanyUuidGreaterThan(String value) {
            addCriterion("company_uuid >", value, "companyUuid");
            return (Criteria) this;
        }

        public Criteria andCompanyUuidGreaterThanOrEqualTo(String value) {
            addCriterion("company_uuid >=", value, "companyUuid");
            return (Criteria) this;
        }

        public Criteria andCompanyUuidLessThan(String value) {
            addCriterion("company_uuid <", value, "companyUuid");
            return (Criteria) this;
        }

        public Criteria andCompanyUuidLessThanOrEqualTo(String value) {
            addCriterion("company_uuid <=", value, "companyUuid");
            return (Criteria) this;
        }

        public Criteria andCompanyUuidLike(String value) {
            addCriterion("company_uuid like", value, "companyUuid");
            return (Criteria) this;
        }

        public Criteria andCompanyUuidNotLike(String value) {
            addCriterion("company_uuid not like", value, "companyUuid");
            return (Criteria) this;
        }

        public Criteria andCompanyUuidIn(List<String> values) {
            addCriterion("company_uuid in", values, "companyUuid");
            return (Criteria) this;
        }

        public Criteria andCompanyUuidNotIn(List<String> values) {
            addCriterion("company_uuid not in", values, "companyUuid");
            return (Criteria) this;
        }

        public Criteria andCompanyUuidBetween(String value1, String value2) {
            addCriterion("company_uuid between", value1, value2, "companyUuid");
            return (Criteria) this;
        }

        public Criteria andCompanyUuidNotBetween(String value1, String value2) {
            addCriterion("company_uuid not between", value1, value2, "companyUuid");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNull() {
            addCriterion("company_name is null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNotNull() {
            addCriterion("company_name is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameEqualTo(String value) {
            addCriterion("company_name =", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotEqualTo(String value) {
            addCriterion("company_name <>", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThan(String value) {
            addCriterion("company_name >", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThanOrEqualTo(String value) {
            addCriterion("company_name >=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThan(String value) {
            addCriterion("company_name <", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThanOrEqualTo(String value) {
            addCriterion("company_name <=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLike(String value) {
            addCriterion("company_name like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotLike(String value) {
            addCriterion("company_name not like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIn(List<String> values) {
            addCriterion("company_name in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotIn(List<String> values) {
            addCriterion("company_name not in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameBetween(String value1, String value2) {
            addCriterion("company_name between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotBetween(String value1, String value2) {
            addCriterion("company_name not between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuUuidIsNull() {
            addCriterion("shebao_canshu_uuid is null");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuUuidIsNotNull() {
            addCriterion("shebao_canshu_uuid is not null");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuUuidEqualTo(String value) {
            addCriterion("shebao_canshu_uuid =", value, "shebaoCanshuUuid");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuUuidNotEqualTo(String value) {
            addCriterion("shebao_canshu_uuid <>", value, "shebaoCanshuUuid");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuUuidGreaterThan(String value) {
            addCriterion("shebao_canshu_uuid >", value, "shebaoCanshuUuid");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuUuidGreaterThanOrEqualTo(String value) {
            addCriterion("shebao_canshu_uuid >=", value, "shebaoCanshuUuid");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuUuidLessThan(String value) {
            addCriterion("shebao_canshu_uuid <", value, "shebaoCanshuUuid");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuUuidLessThanOrEqualTo(String value) {
            addCriterion("shebao_canshu_uuid <=", value, "shebaoCanshuUuid");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuUuidLike(String value) {
            addCriterion("shebao_canshu_uuid like", value, "shebaoCanshuUuid");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuUuidNotLike(String value) {
            addCriterion("shebao_canshu_uuid not like", value, "shebaoCanshuUuid");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuUuidIn(List<String> values) {
            addCriterion("shebao_canshu_uuid in", values, "shebaoCanshuUuid");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuUuidNotIn(List<String> values) {
            addCriterion("shebao_canshu_uuid not in", values, "shebaoCanshuUuid");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuUuidBetween(String value1, String value2) {
            addCriterion("shebao_canshu_uuid between", value1, value2, "shebaoCanshuUuid");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuUuidNotBetween(String value1, String value2) {
            addCriterion("shebao_canshu_uuid not between", value1, value2, "shebaoCanshuUuid");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuYearcityIsNull() {
            addCriterion("shebao_canshu_yearCity is null");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuYearcityIsNotNull() {
            addCriterion("shebao_canshu_yearCity is not null");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuYearcityEqualTo(String value) {
            addCriterion("shebao_canshu_yearCity =", value, "shebaoCanshuYearcity");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuYearcityNotEqualTo(String value) {
            addCriterion("shebao_canshu_yearCity <>", value, "shebaoCanshuYearcity");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuYearcityGreaterThan(String value) {
            addCriterion("shebao_canshu_yearCity >", value, "shebaoCanshuYearcity");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuYearcityGreaterThanOrEqualTo(String value) {
            addCriterion("shebao_canshu_yearCity >=", value, "shebaoCanshuYearcity");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuYearcityLessThan(String value) {
            addCriterion("shebao_canshu_yearCity <", value, "shebaoCanshuYearcity");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuYearcityLessThanOrEqualTo(String value) {
            addCriterion("shebao_canshu_yearCity <=", value, "shebaoCanshuYearcity");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuYearcityLike(String value) {
            addCriterion("shebao_canshu_yearCity like", value, "shebaoCanshuYearcity");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuYearcityNotLike(String value) {
            addCriterion("shebao_canshu_yearCity not like", value, "shebaoCanshuYearcity");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuYearcityIn(List<String> values) {
            addCriterion("shebao_canshu_yearCity in", values, "shebaoCanshuYearcity");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuYearcityNotIn(List<String> values) {
            addCriterion("shebao_canshu_yearCity not in", values, "shebaoCanshuYearcity");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuYearcityBetween(String value1, String value2) {
            addCriterion("shebao_canshu_yearCity between", value1, value2, "shebaoCanshuYearcity");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuYearcityNotBetween(String value1, String value2) {
            addCriterion("shebao_canshu_yearCity not between", value1, value2, "shebaoCanshuYearcity");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuStarttimeIsNull() {
            addCriterion("shebao_canshu_startTime is null");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuStarttimeIsNotNull() {
            addCriterion("shebao_canshu_startTime is not null");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuStarttimeEqualTo(Date value) {
            addCriterion("shebao_canshu_startTime =", value, "shebaoCanshuStarttime");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuStarttimeNotEqualTo(Date value) {
            addCriterion("shebao_canshu_startTime <>", value, "shebaoCanshuStarttime");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuStarttimeGreaterThan(Date value) {
            addCriterion("shebao_canshu_startTime >", value, "shebaoCanshuStarttime");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuStarttimeGreaterThanOrEqualTo(Date value) {
            addCriterion("shebao_canshu_startTime >=", value, "shebaoCanshuStarttime");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuStarttimeLessThan(Date value) {
            addCriterion("shebao_canshu_startTime <", value, "shebaoCanshuStarttime");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuStarttimeLessThanOrEqualTo(Date value) {
            addCriterion("shebao_canshu_startTime <=", value, "shebaoCanshuStarttime");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuStarttimeIn(List<Date> values) {
            addCriterion("shebao_canshu_startTime in", values, "shebaoCanshuStarttime");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuStarttimeNotIn(List<Date> values) {
            addCriterion("shebao_canshu_startTime not in", values, "shebaoCanshuStarttime");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuStarttimeBetween(Date value1, Date value2) {
            addCriterion("shebao_canshu_startTime between", value1, value2, "shebaoCanshuStarttime");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuStarttimeNotBetween(Date value1, Date value2) {
            addCriterion("shebao_canshu_startTime not between", value1, value2, "shebaoCanshuStarttime");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuEndtimeIsNull() {
            addCriterion("shebao_canshu_endTime is null");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuEndtimeIsNotNull() {
            addCriterion("shebao_canshu_endTime is not null");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuEndtimeEqualTo(Date value) {
            addCriterion("shebao_canshu_endTime =", value, "shebaoCanshuEndtime");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuEndtimeNotEqualTo(Date value) {
            addCriterion("shebao_canshu_endTime <>", value, "shebaoCanshuEndtime");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuEndtimeGreaterThan(Date value) {
            addCriterion("shebao_canshu_endTime >", value, "shebaoCanshuEndtime");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuEndtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("shebao_canshu_endTime >=", value, "shebaoCanshuEndtime");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuEndtimeLessThan(Date value) {
            addCriterion("shebao_canshu_endTime <", value, "shebaoCanshuEndtime");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuEndtimeLessThanOrEqualTo(Date value) {
            addCriterion("shebao_canshu_endTime <=", value, "shebaoCanshuEndtime");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuEndtimeIn(List<Date> values) {
            addCriterion("shebao_canshu_endTime in", values, "shebaoCanshuEndtime");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuEndtimeNotIn(List<Date> values) {
            addCriterion("shebao_canshu_endTime not in", values, "shebaoCanshuEndtime");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuEndtimeBetween(Date value1, Date value2) {
            addCriterion("shebao_canshu_endTime between", value1, value2, "shebaoCanshuEndtime");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuEndtimeNotBetween(Date value1, Date value2) {
            addCriterion("shebao_canshu_endTime not between", value1, value2, "shebaoCanshuEndtime");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuCellingIsNull() {
            addCriterion("shebao_canshu_celling is null");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuCellingIsNotNull() {
            addCriterion("shebao_canshu_celling is not null");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuCellingEqualTo(Double value) {
            addCriterion("shebao_canshu_celling =", value, "shebaoCanshuCelling");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuCellingNotEqualTo(Double value) {
            addCriterion("shebao_canshu_celling <>", value, "shebaoCanshuCelling");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuCellingGreaterThan(Double value) {
            addCriterion("shebao_canshu_celling >", value, "shebaoCanshuCelling");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuCellingGreaterThanOrEqualTo(Double value) {
            addCriterion("shebao_canshu_celling >=", value, "shebaoCanshuCelling");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuCellingLessThan(Double value) {
            addCriterion("shebao_canshu_celling <", value, "shebaoCanshuCelling");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuCellingLessThanOrEqualTo(Double value) {
            addCriterion("shebao_canshu_celling <=", value, "shebaoCanshuCelling");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuCellingIn(List<Double> values) {
            addCriterion("shebao_canshu_celling in", values, "shebaoCanshuCelling");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuCellingNotIn(List<Double> values) {
            addCriterion("shebao_canshu_celling not in", values, "shebaoCanshuCelling");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuCellingBetween(Double value1, Double value2) {
            addCriterion("shebao_canshu_celling between", value1, value2, "shebaoCanshuCelling");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuCellingNotBetween(Double value1, Double value2) {
            addCriterion("shebao_canshu_celling not between", value1, value2, "shebaoCanshuCelling");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuFloorIsNull() {
            addCriterion("shebao_canshu_floor is null");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuFloorIsNotNull() {
            addCriterion("shebao_canshu_floor is not null");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuFloorEqualTo(Double value) {
            addCriterion("shebao_canshu_floor =", value, "shebaoCanshuFloor");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuFloorNotEqualTo(Double value) {
            addCriterion("shebao_canshu_floor <>", value, "shebaoCanshuFloor");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuFloorGreaterThan(Double value) {
            addCriterion("shebao_canshu_floor >", value, "shebaoCanshuFloor");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuFloorGreaterThanOrEqualTo(Double value) {
            addCriterion("shebao_canshu_floor >=", value, "shebaoCanshuFloor");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuFloorLessThan(Double value) {
            addCriterion("shebao_canshu_floor <", value, "shebaoCanshuFloor");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuFloorLessThanOrEqualTo(Double value) {
            addCriterion("shebao_canshu_floor <=", value, "shebaoCanshuFloor");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuFloorIn(List<Double> values) {
            addCriterion("shebao_canshu_floor in", values, "shebaoCanshuFloor");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuFloorNotIn(List<Double> values) {
            addCriterion("shebao_canshu_floor not in", values, "shebaoCanshuFloor");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuFloorBetween(Double value1, Double value2) {
            addCriterion("shebao_canshu_floor between", value1, value2, "shebaoCanshuFloor");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuFloorNotBetween(Double value1, Double value2) {
            addCriterion("shebao_canshu_floor not between", value1, value2, "shebaoCanshuFloor");
            return (Criteria) this;
        }

        public Criteria andIsdelIsNull() {
            addCriterion("isdel is null");
            return (Criteria) this;
        }

        public Criteria andIsdelIsNotNull() {
            addCriterion("isdel is not null");
            return (Criteria) this;
        }

        public Criteria andIsdelEqualTo(Boolean value) {
            addCriterion("isdel =", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelNotEqualTo(Boolean value) {
            addCriterion("isdel <>", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelGreaterThan(Boolean value) {
            addCriterion("isdel >", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelGreaterThanOrEqualTo(Boolean value) {
            addCriterion("isdel >=", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelLessThan(Boolean value) {
            addCriterion("isdel <", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelLessThanOrEqualTo(Boolean value) {
            addCriterion("isdel <=", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelIn(List<Boolean> values) {
            addCriterion("isdel in", values, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelNotIn(List<Boolean> values) {
            addCriterion("isdel not in", values, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelBetween(Boolean value1, Boolean value2) {
            addCriterion("isdel between", value1, value2, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelNotBetween(Boolean value1, Boolean value2) {
            addCriterion("isdel not between", value1, value2, "isdel");
            return (Criteria) this;
        }

        public Criteria andCreateNameIsNull() {
            addCriterion("create_name is null");
            return (Criteria) this;
        }

        public Criteria andCreateNameIsNotNull() {
            addCriterion("create_name is not null");
            return (Criteria) this;
        }

        public Criteria andCreateNameEqualTo(String value) {
            addCriterion("create_name =", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotEqualTo(String value) {
            addCriterion("create_name <>", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameGreaterThan(String value) {
            addCriterion("create_name >", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameGreaterThanOrEqualTo(String value) {
            addCriterion("create_name >=", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameLessThan(String value) {
            addCriterion("create_name <", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameLessThanOrEqualTo(String value) {
            addCriterion("create_name <=", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameLike(String value) {
            addCriterion("create_name like", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotLike(String value) {
            addCriterion("create_name not like", value, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameIn(List<String> values) {
            addCriterion("create_name in", values, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotIn(List<String> values) {
            addCriterion("create_name not in", values, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameBetween(String value1, String value2) {
            addCriterion("create_name between", value1, value2, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateNameNotBetween(String value1, String value2) {
            addCriterion("create_name not between", value1, value2, "createName");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andUpdateNameIsNull() {
            addCriterion("update_name is null");
            return (Criteria) this;
        }

        public Criteria andUpdateNameIsNotNull() {
            addCriterion("update_name is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateNameEqualTo(String value) {
            addCriterion("update_name =", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameNotEqualTo(String value) {
            addCriterion("update_name <>", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameGreaterThan(String value) {
            addCriterion("update_name >", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameGreaterThanOrEqualTo(String value) {
            addCriterion("update_name >=", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameLessThan(String value) {
            addCriterion("update_name <", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameLessThanOrEqualTo(String value) {
            addCriterion("update_name <=", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameLike(String value) {
            addCriterion("update_name like", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameNotLike(String value) {
            addCriterion("update_name not like", value, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameIn(List<String> values) {
            addCriterion("update_name in", values, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameNotIn(List<String> values) {
            addCriterion("update_name not in", values, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameBetween(String value1, String value2) {
            addCriterion("update_name between", value1, value2, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameNotBetween(String value1, String value2) {
            addCriterion("update_name not between", value1, value2, "updateName");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andMainUuidLikeInsensitive(String value) {
            addCriterion("upper(main_uuid) like", value.toUpperCase(), "mainUuid");
            return (Criteria) this;
        }

        public Criteria andCompanyUuidLikeInsensitive(String value) {
            addCriterion("upper(company_uuid) like", value.toUpperCase(), "companyUuid");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLikeInsensitive(String value) {
            addCriterion("upper(company_name) like", value.toUpperCase(), "companyName");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuUuidLikeInsensitive(String value) {
            addCriterion("upper(shebao_canshu_uuid) like", value.toUpperCase(), "shebaoCanshuUuid");
            return (Criteria) this;
        }

        public Criteria andShebaoCanshuYearcityLikeInsensitive(String value) {
            addCriterion("upper(shebao_canshu_yearCity) like", value.toUpperCase(), "shebaoCanshuYearcity");
            return (Criteria) this;
        }

        public Criteria andCreateNameLikeInsensitive(String value) {
            addCriterion("upper(create_name) like", value.toUpperCase(), "createName");
            return (Criteria) this;
        }

        public Criteria andUpdateNameLikeInsensitive(String value) {
            addCriterion("upper(update_name) like", value.toUpperCase(), "updateName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table company_shebao_mainbili
     *
     * @mbggenerated do_not_delete_during_merge Mon Nov 21 01:40:05 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table company_shebao_mainbili
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}