package com.unionx.web.company.vo;

import java.io.Serializable;
import java.util.Date;

public class CompanyShebaoMainbili implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_shebao_mainbili.id
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_shebao_mainbili.main_uuid
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    private String mainUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_shebao_mainbili.company_uuid
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    private String companyUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_shebao_mainbili.company_name
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_shebao_mainbili.shebao_canshu_uuid
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    private String shebaoCanshuUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_shebao_mainbili.shebao_canshu_yearCity
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    private String shebaoCanshuYearcity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_shebao_mainbili.shebao_canshu_startTime
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    private Date shebaoCanshuStarttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_shebao_mainbili.shebao_canshu_endTime
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    private Date shebaoCanshuEndtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_shebao_mainbili.shebao_canshu_celling
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    private Double shebaoCanshuCelling;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_shebao_mainbili.shebao_canshu_floor
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    private Double shebaoCanshuFloor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_shebao_mainbili.isdel
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    private Boolean isdel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_shebao_mainbili.create_name
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    private String createName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_shebao_mainbili.create_date
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_shebao_mainbili.update_name
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    private String updateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_shebao_mainbili.update_date
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table company_shebao_mainbili
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_shebao_mainbili.id
     *
     * @return the value of company_shebao_mainbili.id
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_shebao_mainbili.id
     *
     * @param id the value for company_shebao_mainbili.id
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_shebao_mainbili.main_uuid
     *
     * @return the value of company_shebao_mainbili.main_uuid
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    public String getMainUuid() {
        return mainUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_shebao_mainbili.main_uuid
     *
     * @param mainUuid the value for company_shebao_mainbili.main_uuid
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    public void setMainUuid(String mainUuid) {
        this.mainUuid = mainUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_shebao_mainbili.company_uuid
     *
     * @return the value of company_shebao_mainbili.company_uuid
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    public String getCompanyUuid() {
        return companyUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_shebao_mainbili.company_uuid
     *
     * @param companyUuid the value for company_shebao_mainbili.company_uuid
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    public void setCompanyUuid(String companyUuid) {
        this.companyUuid = companyUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_shebao_mainbili.company_name
     *
     * @return the value of company_shebao_mainbili.company_name
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_shebao_mainbili.company_name
     *
     * @param companyName the value for company_shebao_mainbili.company_name
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_shebao_mainbili.shebao_canshu_uuid
     *
     * @return the value of company_shebao_mainbili.shebao_canshu_uuid
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    public String getShebaoCanshuUuid() {
        return shebaoCanshuUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_shebao_mainbili.shebao_canshu_uuid
     *
     * @param shebaoCanshuUuid the value for company_shebao_mainbili.shebao_canshu_uuid
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    public void setShebaoCanshuUuid(String shebaoCanshuUuid) {
        this.shebaoCanshuUuid = shebaoCanshuUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_shebao_mainbili.shebao_canshu_yearCity
     *
     * @return the value of company_shebao_mainbili.shebao_canshu_yearCity
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    public String getShebaoCanshuYearcity() {
        return shebaoCanshuYearcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_shebao_mainbili.shebao_canshu_yearCity
     *
     * @param shebaoCanshuYearcity the value for company_shebao_mainbili.shebao_canshu_yearCity
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    public void setShebaoCanshuYearcity(String shebaoCanshuYearcity) {
        this.shebaoCanshuYearcity = shebaoCanshuYearcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_shebao_mainbili.shebao_canshu_startTime
     *
     * @return the value of company_shebao_mainbili.shebao_canshu_startTime
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    public Date getShebaoCanshuStarttime() {
        return shebaoCanshuStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_shebao_mainbili.shebao_canshu_startTime
     *
     * @param shebaoCanshuStarttime the value for company_shebao_mainbili.shebao_canshu_startTime
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    public void setShebaoCanshuStarttime(Date shebaoCanshuStarttime) {
        this.shebaoCanshuStarttime = shebaoCanshuStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_shebao_mainbili.shebao_canshu_endTime
     *
     * @return the value of company_shebao_mainbili.shebao_canshu_endTime
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    public Date getShebaoCanshuEndtime() {
        return shebaoCanshuEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_shebao_mainbili.shebao_canshu_endTime
     *
     * @param shebaoCanshuEndtime the value for company_shebao_mainbili.shebao_canshu_endTime
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    public void setShebaoCanshuEndtime(Date shebaoCanshuEndtime) {
        this.shebaoCanshuEndtime = shebaoCanshuEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_shebao_mainbili.shebao_canshu_celling
     *
     * @return the value of company_shebao_mainbili.shebao_canshu_celling
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    public Double getShebaoCanshuCelling() {
        return shebaoCanshuCelling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_shebao_mainbili.shebao_canshu_celling
     *
     * @param shebaoCanshuCelling the value for company_shebao_mainbili.shebao_canshu_celling
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    public void setShebaoCanshuCelling(Double shebaoCanshuCelling) {
        this.shebaoCanshuCelling = shebaoCanshuCelling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_shebao_mainbili.shebao_canshu_floor
     *
     * @return the value of company_shebao_mainbili.shebao_canshu_floor
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    public Double getShebaoCanshuFloor() {
        return shebaoCanshuFloor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_shebao_mainbili.shebao_canshu_floor
     *
     * @param shebaoCanshuFloor the value for company_shebao_mainbili.shebao_canshu_floor
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    public void setShebaoCanshuFloor(Double shebaoCanshuFloor) {
        this.shebaoCanshuFloor = shebaoCanshuFloor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_shebao_mainbili.isdel
     *
     * @return the value of company_shebao_mainbili.isdel
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    public Boolean getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_shebao_mainbili.isdel
     *
     * @param isdel the value for company_shebao_mainbili.isdel
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    public void setIsdel(Boolean isdel) {
        this.isdel = isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_shebao_mainbili.create_name
     *
     * @return the value of company_shebao_mainbili.create_name
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    public String getCreateName() {
        return createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_shebao_mainbili.create_name
     *
     * @param createName the value for company_shebao_mainbili.create_name
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    public void setCreateName(String createName) {
        this.createName = createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_shebao_mainbili.create_date
     *
     * @return the value of company_shebao_mainbili.create_date
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_shebao_mainbili.create_date
     *
     * @param createDate the value for company_shebao_mainbili.create_date
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_shebao_mainbili.update_name
     *
     * @return the value of company_shebao_mainbili.update_name
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    public String getUpdateName() {
        return updateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_shebao_mainbili.update_name
     *
     * @param updateName the value for company_shebao_mainbili.update_name
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    public void setUpdateName(String updateName) {
        this.updateName = updateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_shebao_mainbili.update_date
     *
     * @return the value of company_shebao_mainbili.update_date
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_shebao_mainbili.update_date
     *
     * @param updateDate the value for company_shebao_mainbili.update_date
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_shebao_mainbili
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CompanyShebaoMainbili other = (CompanyShebaoMainbili) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getMainUuid() == null ? other.getMainUuid() == null : this.getMainUuid().equals(other.getMainUuid()))
            && (this.getCompanyUuid() == null ? other.getCompanyUuid() == null : this.getCompanyUuid().equals(other.getCompanyUuid()))
            && (this.getCompanyName() == null ? other.getCompanyName() == null : this.getCompanyName().equals(other.getCompanyName()))
            && (this.getShebaoCanshuUuid() == null ? other.getShebaoCanshuUuid() == null : this.getShebaoCanshuUuid().equals(other.getShebaoCanshuUuid()))
            && (this.getShebaoCanshuYearcity() == null ? other.getShebaoCanshuYearcity() == null : this.getShebaoCanshuYearcity().equals(other.getShebaoCanshuYearcity()))
            && (this.getShebaoCanshuStarttime() == null ? other.getShebaoCanshuStarttime() == null : this.getShebaoCanshuStarttime().equals(other.getShebaoCanshuStarttime()))
            && (this.getShebaoCanshuEndtime() == null ? other.getShebaoCanshuEndtime() == null : this.getShebaoCanshuEndtime().equals(other.getShebaoCanshuEndtime()))
            && (this.getShebaoCanshuCelling() == null ? other.getShebaoCanshuCelling() == null : this.getShebaoCanshuCelling().equals(other.getShebaoCanshuCelling()))
            && (this.getShebaoCanshuFloor() == null ? other.getShebaoCanshuFloor() == null : this.getShebaoCanshuFloor().equals(other.getShebaoCanshuFloor()))
            && (this.getIsdel() == null ? other.getIsdel() == null : this.getIsdel().equals(other.getIsdel()))
            && (this.getCreateName() == null ? other.getCreateName() == null : this.getCreateName().equals(other.getCreateName()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateName() == null ? other.getUpdateName() == null : this.getUpdateName().equals(other.getUpdateName()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_shebao_mainbili
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getMainUuid() == null) ? 0 : getMainUuid().hashCode());
        result = prime * result + ((getCompanyUuid() == null) ? 0 : getCompanyUuid().hashCode());
        result = prime * result + ((getCompanyName() == null) ? 0 : getCompanyName().hashCode());
        result = prime * result + ((getShebaoCanshuUuid() == null) ? 0 : getShebaoCanshuUuid().hashCode());
        result = prime * result + ((getShebaoCanshuYearcity() == null) ? 0 : getShebaoCanshuYearcity().hashCode());
        result = prime * result + ((getShebaoCanshuStarttime() == null) ? 0 : getShebaoCanshuStarttime().hashCode());
        result = prime * result + ((getShebaoCanshuEndtime() == null) ? 0 : getShebaoCanshuEndtime().hashCode());
        result = prime * result + ((getShebaoCanshuCelling() == null) ? 0 : getShebaoCanshuCelling().hashCode());
        result = prime * result + ((getShebaoCanshuFloor() == null) ? 0 : getShebaoCanshuFloor().hashCode());
        result = prime * result + ((getIsdel() == null) ? 0 : getIsdel().hashCode());
        result = prime * result + ((getCreateName() == null) ? 0 : getCreateName().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateName() == null) ? 0 : getUpdateName().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        return result;
    }
}