package com.unionx.web.company.dao;

import com.unionx.web.company.vo.CompanyShebaoMainbili;
import com.unionx.web.company.vo.CompanyShebaoMainbiliCriteria;

import java.util.HashMap;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
@Repository
public interface CompanyShebaoMainbiliMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_shebao_mainbili
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    int countByExample(CompanyShebaoMainbiliCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_shebao_mainbili
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    int deleteByExample(CompanyShebaoMainbiliCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_shebao_mainbili
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_shebao_mainbili
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    int insert(CompanyShebaoMainbili record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_shebao_mainbili
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    int insertSelective(CompanyShebaoMainbili record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_shebao_mainbili
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    List<CompanyShebaoMainbili> selectByExample(CompanyShebaoMainbiliCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_shebao_mainbili
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    CompanyShebaoMainbili selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_shebao_mainbili
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    int updateByExampleSelective(@Param("record") CompanyShebaoMainbili record, @Param("example") CompanyShebaoMainbiliCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_shebao_mainbili
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    int updateByExample(@Param("record") CompanyShebaoMainbili record, @Param("example") CompanyShebaoMainbiliCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_shebao_mainbili
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    int updateByPrimaryKeySelective(CompanyShebaoMainbili record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_shebao_mainbili
     *
     * @mbggenerated Mon Nov 21 01:40:05 CST 2016
     */
    int updateByPrimaryKey(CompanyShebaoMainbili record);
    
    long countByEnterpriseSB(HashMap<String,String>map);
}